### ISSUE TITLE
Implement Login Steam API 

### ISSUE THREAD

**Issue by TheDedemon** [Structed/godot-playfab#133]
**Implement API in order to login with Steam.**

**Docs**: https://learn.microsoft.com/en-us/rest/api/playfab/client/authentication/login-with-steam?view=playfab-rest

- [x] Implement new request

- [x] Update documentation
    - [x] Add example with a Steam Auth Session Ticket

    - [x] Add example with a Steam Auth Ticket for Web API

<br />

**Additional notes:**
- Don't forget to cancel Steam Auth Tickets in the examples.

**Comment by Structed** [comment]
Perhaps it would make sense to create a separate package for this, as there are hard dependencies on GodotSteam?

**Comment by TheDedemon** [comment]
**GodotSteam** is not required in order to login into PlayFab with Steam. Only string and bools are needed. I just use GodotSteam to do my tests easily (I don't want to do my own wrapper 😄) and give an example for other developers.

**Comment by Structed** [comment]
I see, I just figured it might be cool to add a package that wraps what you get from GodotSteam!

**Comment by TheDedemon** [comment]
Hmm, I don't know. I used a "wrapper" in my test that I will show in the documentation.
Making a package for that is maybe over-engineered. Furthermore, GodotSteam or the SteamSDK (C++) is very big (auth, leadeboard, pvp, ...) and contains many subtleties that developers should be aware (session begin / end, auth create / cancel, ...)

**Comment by Structed** [comment]
Implemented with #132
