### ISSUE TITLE
Events are dropped if batch size exceeds the playfab api limits

### ISSUE THREAD

**Issue by OSeraph** [Structed/godot-playfab#144]
### godot-playfab version

1.2.0

### Godot version

4.3.1

### System information

Windows 11

### Issue description

[If the telemetry or playstream event batches exceed the playfab API limits the events will not be accepted. ](https://learn.microsoft.com/en-us/rest/api/playfab/events/play-stream-events/write-telemetry-events?view=playfab-rest)

This can happen if a user of this addon accumulates a list of events where n > 200 to be sent before the authentication response is received and sends them after authentication is received.

Once the user is logged in this should not happen as the addon should be sending events every 5 seconds. But for apps that generate a lot of events this can still occur.

### Steps to reproduce

* Start your  game/project
* Initiate playfab login
* Generate 201 events before login response is received
* Send the 201 events to `PlayFabManager.event.batch_title_player_telemetry_event` or `PlayFabManager.event.batch_title_player_playstream_event`
* Observe in playfab analytics that the events were not received.

### Minimal reproduction project

I do not have a minimal reproduction project however, I did fix this "bug" in my own project and the solution below is what worked for me. 
I would put up a pull request myself but I don't have access to do so for this repository.
```
diff --git a/addons/godot-playfab/PlayFabEvent.gd b/addons/godot-playfab/PlayFabEvent.gd
index f90b5b3..2dbb726 100644
--- a/addons/godot-playfab/PlayFabEvent.gd
+++ b/addons/godot-playfab/PlayFabEvent.gd
@@ -149,9 +149,19 @@ func _flush_playstream_event_batch():
                return

        var request = WriteEventsRequest.new()
-       request.Events = playstream_event_batch
+       # Playfab API allows a max of 200 events
+       var oversized_batch = playstream_event_batch._Items.size() > 200
+       if oversized_batch: 
+               request.Events = playstream_event_batch._Items.slice(0, 199)
+               playstream_event_batch._Items = playstream_event_batch._Items.slice(200)
+       else:
+               request.Events = playstream_event_batch
+
        event_playstream_write_events(request, Callable(self, "_on_playstream_batch_flush"))
-       playstream_event_batch.clear()
+       
+       if not oversized_batch: # Retain events that cannot be sent on this flush
+               playstream_event_batch.clear()
+       
        print_debug("Flushed playstream batch")


@@ -163,9 +173,17 @@ func _flush_telemetry_event_batch():
                return

        var request = WriteEventsRequest.new()
-       request.Events = telemetry_event_batch
+       
+       var oversized_batch = telemetry_event_batch._Items.size() > 200
+       if oversized_batch: 
+               request.Events = telemetry_event_batch._Items.slice(0, 199)
+               telemetry_event_batch._Items = telemetry_event_batch._Items.slice(200)
+       else:
+               request.Events = telemetry_event_batch
+
        event_telemetry_write_events(request, Callable(self, "_on_telemetry_batch_flush"))
-       telemetry_event_batch.clear()
+       if not oversized_batch:
+               telemetry_event_batch.clear()
        print_debug("Flushed telemetry batch")
```

**Comment by Structed** [comment]
Hi @OSeraph! Thank you very much for reporting this and suggesting a solution!

I did take a bit of another, simpler, route to fix this for now. Now, it's just not possible to add more than 200 events to the batch anymore. A warning is pushed if you try to add more instead.

One reason to not allow more than 200 is to not run into a possible problem with an ever increasing batch - which would eventually lead to a memory overflow.

One could add safeguards against runaway memory consumption, but that's a more complex implementation, e.g. with file system persistence. It could be tackled if there's a higher demand and someone suggests a solution.

Thanks again and I hope this new solution works for your use-case as well. Please free to suggest how it could be done differently!

**Comment by Structed** [comment]
For reference: #32
