### ISSUE TITLE
UUID.v4() doesn't seem work on web export

### ISSUE THREAD

**Issue by Velkaras** [Structed/godot-playfab#148]
### godot-playfab version

1.3.0

### Godot version

4.3

### System information

Windows 11

### Issue description

UUID.v4() doesn't seem work on web export

![image](https://github.com/user-attachments/assets/bcdb2c43-7212-40da-96c9-ecc8e1667aca)

### Steps to reproduce

Exporting and running on the web

### Minimal reproduction project

[project.zip](https://github.com/user-attachments/files/18157260/project.zip)

**Comment by Structed** [comment]
@Velkaras which browser and version did you use? Which platform are you running on?

**Comment by Velkaras** [comment]
Firefox 133.0.3(64-bit) and Vivaldi 7.0.3495.26 (Stable channel) (64-bit)

**Comment by Structed** [comment]
I cannot reproduce when debugging locally with

- Microsoft Edge Version 131.0.2903.99 (Official build) (64-bit)
- Firefox 133.0.3 (64-bit)

![image](https://github.com/user-attachments/assets/7eebe01c-d40a-40de-9f49-23de2b1efe54)


What's your exact hosting repro?

**Comment by Velkaras** [comment]
I simply run npx http-server
![Screenshot 2024-12-17 000449](https://github.com/user-attachments/assets/4d94e969-7a5b-4786-a7d9-12893713fee7)

**Comment by Structed** [comment]
can you please try the built-in webserver as well and perhaps another one?

**Comment by Structed** [comment]
Also can't repo with http-server version: 14.1.1

![image](https://github.com/user-attachments/assets/3afc2a14-b49e-42e3-a18a-381917a5d3ea)

**Comment by Velkaras** [comment]
I tried apache server 2.4, simple web server itried htpp-server with enabling cors, gzip, brotli settings, I uploaded on itch.io, All of them didn't worked.

**Comment by Structed** [comment]
Interesting. Can you please share which export settings you are using?

Did you also try the built-in debug?

**Comment by Structed** [comment]
PR: to change uuid lib: #149
