### ISSUE TITLE
Timestamp of Events

### ISSUE THREAD

**Issue by ReneHabermann** [Structed/godot-playfab#65]
Hi, i just wondered if the timestamp in the events is the ingestion time, or when the event is created.
For me, the only really useful timestamp is the event creation time, as i expect a timeout+retry and general latency can mess with event order and timing.
Which one is it?

Lokking forward to trying it :)

**Comment by Structed** [comment]
The time will automatically be set to the ingestion time, unless you set it.

I agree that it should be set by the SDK automatically by default. It can then be overridden by the user if needed or can be removed if there is a need to set it on ingestion.

**Comment by Structed** [comment]
@ReneHabermann Added functionality to set the time locally and made it a default.
