### ISSUE TITLE
Potential crashes for release builds due to yields

### ISSUE THREAD

**Issue by ReneHabermann** [Structed/godot-playfab#88]
Hi, i'm seeing this error

`E 0:00:12.968   GDScriptFunctionState::resume: Resumed function '_http_request()' after yield, but script is gone. At script: res://addons/godot-playfab/PlayFabHttp.gd:61
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  modules\gdscript\gdscript_function.cpp:1795 @ GDScriptFunctionState::resume()`
  
  If i'm not mistaken, this leads to a crash on release builds. So there is a risk with using yields. Local timers or signals might be an alternative here.

**Comment by Structed** [comment]
@ReneHabermann can you please provide steps to repo? I can imagine how you got there and I have a potential fix, but I was unable to reproduce. And I need a repro to confirm my fix ☺️

**Comment by Structed** [comment]
There are no `yield` statements anymore in the latest version of godot-playfab.
