### ISSUE TITLE
Login and registration does not work on HTML5 build

### ISSUE THREAD

**Issue by zymsbgt** [Structed/godot-playfab#97]
Steps to reproduce: 
1. Create an export preset for HTML5
2. Close the Export window
3. Click the HTML5 icon on the top right corner of the editor, next to the stop button
4. Godot will build the project on HTML5 and open a new tab with the game
5. Once loaded, login or register with an account

Expected result: Login or registration works successfully

Actual result: The project gets stuck at loading indicator

**Comment by Structed** [comment]
Thanks for your report! Please let me know which versions you used!

Godot and godot-playfab

**Comment by zymsbgt** [comment]
I am using Godot Mono 3.5.1 and godot-playfab 0.3.2

**Comment by Structed** [comment]
@zymsbgt can you confirm your browser developer tools yield the same errors?

```
WARNING: incorrect header check
  at: decompress_dynamic (core/io/compression.cpp:244) - incorrect header 
ERROR: Decompression failed.
  at: _call_PoolByteArray_decompress_dynamic (core/variant_call.cpp:677) - Method failed.
ERROR: Error parsing JSON at line 0: 
  at: parse (core/bind/core_bind.cpp:3267) - Error parsing JSON at line 0: 
```
